### ISSUE TITLE
Java Example

### ISSUE THREAD

**Issue by stevesloka** [awslabs/amazon-elasticsearch-lambda-samples#3]
Do you have any hints on how to setup the same example with the java sdk? I'm trying to created the signed requests so I can write to Elastic. If you can even point to the classes in the java sdk, that would be a help. I would actually help write back an example in a PR.

**Comment by malpani** [comment]
Jest might be useful here. Relevant links
[1] https://github.com/searchbox-io/Jest/issues/248 
[2] https://github.com/inreachventures/aws-signing-request-interceptor

**Comment by stevesloka** [comment]
But what if I don't want to use Jest? I have my app written to use plain rest calls. Does the sdk facilitate a way to sign the requests (or generate the headers) for me? I want to stick to the sdk so as things change, I don't have to constantly update custom code. 

Is there an HttpRequest method in the sdk?

**Comment by stevesloka** [comment]
Hey @malpani I updated to use Jest and the request interceptor and that works. BUT, when I use credentials from "EnvironmentVariableCredentialsProvider" I get at 403 "message":"The security token included in the request is invalid.".. When I use my personal credentials it works fine. I've setup my execution role to have the following permissions (note I've removed my private data inside the carrots). Is there anything further to setup to allow my execution role to access elastic?

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "es:*",
            "Resource": [
                "arn:aws:es:us-east-1:<account>:domain/<domain>/*"
            ]
        }
    ]
}
```

**Comment by malpani** [comment]
Native java SDK relies on binary protocol and I don't think it has an HttpClient.

Regarding the error you see, I have personally not used the request interceptor and it might be worth reporting an issue at https://github.com/inreachventures/aws-signing-request-interceptor with the code snippet for invoking it

**Comment by jrask** [comment]
Any updates on this? Is it really that hard to accomplish this from Java?

**Comment by stevesloka** [comment]
I was able to get it working with the Jest client and using the REST interface.
